import { CategoryMeta, ToolCategory } from "./types";

export const CATEGORIES: Record<ToolCategory, CategoryMeta> = {
  text: {
    id: "text",
    name: "Text Utilities",
    slug: "text",
    description: "Format, analyze, clean, transform, count and manipulate plain text strings and multiline content.",
    iconName: "Type",
    accentColor: "from-blue-500/20 to-cyan-500/20",
    badgeBg: "bg-blue-500/10 dark:bg-blue-500/15",
    badgeBorder: "border-blue-500/30",
    badgeText: "text-blue-600 dark:text-blue-400",
    totalTools: 12,
  },
  json: {
    id: "json",
    name: "JSON Tools",
    slug: "json",
    description: "Format, validate, minify, inspect, sort, flatten, diff, query and convert JSON and CSV data.",
    iconName: "Braces",
    accentColor: "from-amber-500/20 to-yellow-500/20",
    badgeBg: "bg-amber-500/10 dark:bg-amber-500/15",
    badgeBorder: "border-amber-500/30",
    badgeText: "text-amber-600 dark:text-amber-400",
    totalTools: 14,
  },
  developer: {
    id: "developer",
    name: "Developer Utilities",
    slug: "developer",
    description: "Cryptographically strong UUIDs, random IDs, regex testers, timestamps, timezone converters, URL and cron analyzers.",
    iconName: "Code2",
    accentColor: "from-indigo-500/20 to-violet-500/20",
    badgeBg: "bg-indigo-500/10 dark:bg-indigo-500/15",
    badgeBorder: "border-indigo-500/30",
    badgeText: "text-indigo-600 dark:text-indigo-400",
    totalTools: 12,
  },
  encoding: {
    id: "encoding",
    name: "Encoding & Decoding",
    slug: "encoding",
    description: "Encode and decode Base64, Base64URL, URL components, HTML entities and Hexadecimal data securely in your browser.",
    iconName: "Binary",
    accentColor: "from-emerald-500/20 to-teal-500/20",
    badgeBg: "bg-emerald-500/10 dark:bg-emerald-500/15",
    badgeBorder: "border-emerald-500/30",
    badgeText: "text-emerald-600 dark:text-emerald-400",
    totalTools: 10,
  },
  security: {
    id: "security",
    name: "Security Tools",
    slug: "security",
    description: "Generate, inspect, encrypt, sign and verify passwords, hashes, tokens and key material locally with browser-native security APIs.",
    iconName: "ShieldCheck",
    accentColor: "from-rose-500/20 to-orange-500/20",
    badgeBg: "bg-rose-500/10 dark:bg-rose-500/15",
    badgeBorder: "border-rose-500/30",
    badgeText: "text-rose-600 dark:text-rose-400",
    totalTools: 18,
  },
  sql: {
    id: "sql",
    name: "SQL Tools",
    slug: "sql",
    description: "Format, validate, convert, generate and explain supported SQL structures with explicit dialect and safety guidance.",
    iconName: "Database",
    accentColor: "from-violet-500/20 to-purple-500/20",
    badgeBg: "bg-violet-500/10 dark:bg-violet-500/15",
    badgeBorder: "border-violet-500/30",
    badgeText: "text-violet-600 dark:text-violet-400",
    totalTools: 15,
  },
  data: {
    id: "data",
    name: "CSV & Data Tools",
    slug: "data",
    description: "Parse, validate, inspect, transform and profile CSV, TSV, JSON and JSON Lines using one shared browser-only tabular data engine.",
    iconName: "Table2",
    accentColor: "from-cyan-500/20 to-sky-500/20",
    badgeBg: "bg-cyan-500/10 dark:bg-cyan-500/15",
    badgeBorder: "border-cyan-500/30",
    badgeText: "text-cyan-600 dark:text-cyan-400",
    totalTools: 24,
  },
  api: {
    id: "api", name: "API Tools", slug: "api",
    description: "Build, parse, inspect and test HTTP/API requests with explicit browser and proxy boundaries.",
    iconName: "Brackets", accentColor: "from-fuchsia-500/20 to-violet-500/20", badgeBg: "bg-fuchsia-500/10 dark:bg-fuchsia-500/15", badgeBorder: "border-fuchsia-500/30", badgeText: "text-fuchsia-600 dark:text-fuchsia-400",
    totalTools: 0, plannedTools: 10, published: false,
  },
  image: {
    id: "image", name: "Image Tools", slug: "image",
    description: "Resize, compress, convert, crop and inspect images locally using browser-native graphics APIs.",
    iconName: "Image", accentColor: "from-pink-500/20 to-rose-500/20", badgeBg: "bg-pink-500/10 dark:bg-pink-500/15", badgeBorder: "border-pink-500/30", badgeText: "text-pink-600 dark:text-pink-400",
    totalTools: 0, plannedTools: 10, published: false,
  },
  pdf: {
    id: "pdf", name: "PDF Tools", slug: "pdf",
    description: "Inspect and transform PDF documents locally without uploading document bytes to DevBite.",
    iconName: "FileText", accentColor: "from-red-500/20 to-orange-500/20", badgeBg: "bg-red-500/10 dark:bg-red-500/15", badgeBorder: "border-red-500/30", badgeText: "text-red-600 dark:text-red-400",
    totalTools: 0, plannedTools: 10, published: false,
  },
  file: {
    id: "file", name: "File Tools", slug: "file",
    description: "Inspect, hash, measure and convert local files without sending their contents to DevBite servers.",
    iconName: "Files", accentColor: "from-lime-500/20 to-emerald-500/20", badgeBg: "bg-lime-500/10 dark:bg-lime-500/15", badgeBorder: "border-lime-500/30", badgeText: "text-lime-700 dark:text-lime-400",
    totalTools: 5, plannedTools: 10, published: true,
  },
  networking: {
    id: "networking", name: "Networking Tools", slug: "networking",
    description: "Calculate and inspect addresses, subnets, DNS records and common network identifiers.",
    iconName: "Network", accentColor: "from-sky-500/20 to-blue-500/20", badgeBg: "bg-sky-500/10 dark:bg-sky-500/15", badgeBorder: "border-sky-500/30", badgeText: "text-sky-600 dark:text-sky-400",
    totalTools: 0, plannedTools: 10, published: false,
  },
  generation: {
    id: "generation", name: "Generation Tools", slug: "generation",
    description: "Generate representative text, identifiers, mock data, SQL and color palettes entirely in the browser.",
    iconName: "WandSparkles", accentColor: "from-yellow-500/20 to-amber-500/20", badgeBg: "bg-yellow-500/10 dark:bg-yellow-500/15", badgeBorder: "border-yellow-500/30", badgeText: "text-yellow-700 dark:text-yellow-400",
    totalTools: 0, plannedTools: 10, published: false,
  },
};

export const ALL_CATEGORIES: CategoryMeta[] = Object.values(CATEGORIES);
export const CATEGORY_LIST: CategoryMeta[] = ALL_CATEGORIES.filter((category) => category.published !== false);
