import { DataTable } from "../data";
import type { SqlDialect } from "./index";

export type KeywordCase = "upper" | "lower" | "preserve";
const KEYWORDS = new Set("select from where and or insert into values update set delete create table join inner left right full outer on as group by order having limit offset union all distinct case when then else end null is not like in exists primary key references default unique check returning with asc desc".split(" "));
const CLAUSES = ["SELECT", "FROM", "WHERE", "GROUP BY", "HAVING", "ORDER BY", "LIMIT", "OFFSET", "VALUES", "SET", "RETURNING", "UNION", "LEFT JOIN", "RIGHT JOIN", "FULL JOIN", "INNER JOIN", "JOIN"];

export interface SqlToken { type: "word" | "string" | "quoted" | "comment" | "symbol" | "space"; value: string; position: number }
export function tokenizeSql(sql: string): SqlToken[] {
  const tokens: SqlToken[] = []; let index = 0;
  while (index < sql.length) { const start = index; const char = sql[index];
    if (/\s/.test(char)) { while (/\s/.test(sql[index] ?? "")) index++; tokens.push({ type: "space", value: sql.slice(start, index), position: start }); continue; }
    if (char === "-" && sql[index + 1] === "-") { index += 2; while (index < sql.length && sql[index] !== "\n") index++; tokens.push({ type: "comment", value: sql.slice(start, index), position: start }); continue; }
    if (char === "/" && sql[index + 1] === "*") { index += 2; while (index < sql.length && !(sql[index] === "*" && sql[index + 1] === "/")) index++; if (index >= sql.length) throw new Error(`Unclosed block comment at character ${start + 1}.`); index += 2; tokens.push({ type: "comment", value: sql.slice(start, index), position: start }); continue; }
    if (["'", '"', "`", "["].includes(char)) { const close = char === "[" ? "]" : char; index++; while (index < sql.length) { if (sql[index] === close) { if (sql[index + 1] === close && close !== "]") { index += 2; continue; } index++; break; } index++; } if (sql[index - 1] !== close) throw new Error(`Unclosed quoted value at character ${start + 1}.`); tokens.push({ type: char === "'" ? "string" : "quoted", value: sql.slice(start, index), position: start }); continue; }
    if (/[A-Za-z0-9_$]/.test(char)) { index++; while (/[A-Za-z0-9_$]/.test(sql[index] ?? "")) index++; tokens.push({ type: "word", value: sql.slice(start, index), position: start }); continue; }
    index++; tokens.push({ type: "symbol", value: char, position: start });
  } return tokens;
}

function keyword(value: string, casing: KeywordCase) { if (!KEYWORDS.has(value.toLowerCase())) return value; return casing === "upper" ? value.toUpperCase() : casing === "lower" ? value.toLowerCase() : value; }
export function minifySql(sql: string) { const tokens = tokenizeSql(sql).filter((token) => token.type !== "comment" && token.type !== "space"); let output = ""; tokens.forEach((token, index) => { const previous = tokens[index - 1]; const needSpace = previous && ((["word", "string", "quoted"].includes(previous.type) && ["word", "string", "quoted"].includes(token.type)) || (previous.value === ")" && token.type === "word") || (previous.type === "word" && token.value === "(" && previous.value.toUpperCase() === "IN")); output += `${needSpace ? " " : ""}${token.value}`; }); return output.trim(); }

export function formatSql(sql: string, options: { keywordCase?: KeywordCase; indent?: number } = {}) { const casing = options.keywordCase ?? "upper"; const indent = " ".repeat(options.indent ?? 2); const compact = minifySql(sql); const tokens = tokenizeSql(compact).filter((token) => token.type !== "space"); let output = ""; let depth = 0; const newline = () => { output = output.trimEnd(); if (output) output += "\n" + indent.repeat(Math.max(0, depth)); };
  for (let index = 0; index < tokens.length; index++) { const token = tokens[index]; const two = `${token.value.toUpperCase()} ${tokens[index + 1]?.value.toUpperCase()}`; const clause = CLAUSES.includes(two) ? two : CLAUSES.includes(token.value.toUpperCase()) ? token.value.toUpperCase() : "";
    if (clause && output && !["AND", "OR"].includes(clause)) newline();
    if (clause === two) { output += `${keyword(token.value, casing)} ${keyword(tokens[++index].value, casing)} `; continue; }
    if (token.value === "(") { depth++; output += "("; }
    else if (token.value === ")") { depth = Math.max(0, depth - 1); output = output.trimEnd() + ")"; }
    else if (token.value === ",") { output = output.trimEnd() + ",\n" + indent.repeat(depth + 1); }
    else if (token.value === ";") output = output.trimEnd() + ";\n";
    else { const value = token.type === "word" ? keyword(token.value, casing) : token.value; const previous = output.at(-1); const noSpace = !output || previous === "(" || previous === "." || token.value === "."; output += `${noSpace ? "" : " "}${value}`; }
  } return output.trim(); }

export function validateSql(sql: string, dialect: SqlDialect = "generic") { const diagnostics: string[] = []; if (!sql.trim()) diagnostics.push("SQL input is empty."); let tokens: SqlToken[] = []; try { tokens = tokenizeSql(sql); } catch (error) { diagnostics.push(error instanceof Error ? error.message : "Unable to tokenize SQL."); }
  const significant = tokens.filter((token) => token.type !== "space" && token.type !== "comment"); let depth = 0; significant.forEach((token) => { if (token.value === "(") depth++; if (token.value === ")") depth--; if (depth < 0) { diagnostics.push(`Unexpected closing parenthesis at character ${token.position + 1}.`); depth = 0; } }); if (depth) diagnostics.push(`${depth} opening parenthesis${depth === 1 ? " is" : "es are"} not closed.`);
  const first = significant[0]?.value.toUpperCase(); if (first && !["SELECT", "INSERT", "UPDATE", "DELETE", "CREATE", "ALTER", "DROP", "WITH", "MERGE", "TRUNCATE"].includes(first)) diagnostics.push(`Unsupported or unrecognized starting keyword: ${first}.`);
  if (first === "SELECT" && !significant.some((token) => token.value.toUpperCase() === "FROM")) diagnostics.push("SELECT has no FROM clause. Constant-only SELECT statements may still be valid in some dialects.");
  return { valid: diagnostics.length === 0, diagnostics, dialect, scope: "Structural validation only; vendor-specific grammar is not executed." };
}

export function quoteIdentifier(identifier: string, dialect: SqlDialect) { if (!/^[A-Za-z_][A-Za-z0-9_$]*(?:\.[A-Za-z_][A-Za-z0-9_$]*)*$/.test(identifier)) throw new Error(`Invalid SQL identifier: ${identifier}`); const quote = dialect === "mysql" ? ["`", "`"] : dialect === "sql-server" ? ["[", "]"] : ['"', '"']; return identifier.split(".").map((part) => `${quote[0]}${part}${quote[1]}`).join("."); }
export function sqlLiteral(value: string, type: "text" | "number" | "boolean" | "null" = "text", dialect: SqlDialect = "generic") { if (type === "null" || value.toLowerCase() === "null") return "NULL"; if (type === "number") { if (!/^-?(?:\d+|\d*\.\d+)$/.test(value.trim())) throw new Error(`Invalid numeric value: ${value}`); return value.trim(); } if (type === "boolean") return /^(true|1)$/i.test(value.trim()) ? (dialect === "sql-server" ? "1" : "TRUE") : (dialect === "sql-server" ? "0" : "FALSE"); return `'${value.replaceAll("'", "''")}'`; }
export function tableToInsert(table: DataTable, tableName: string, dialect: SqlDialect = "generic") { if (!table.rows.length) throw new Error("At least one data row is required."); const target = quoteIdentifier(tableName, dialect); const columns = table.headers.map((header) => quoteIdentifier(header, dialect)).join(", "); return table.rows.map((row) => `INSERT INTO ${target} (${columns}) VALUES (${row.map((value) => sqlLiteral(value, value === "" ? "null" : /^-?\d+(?:\.\d+)?$/.test(value) ? "number" : /^(true|false)$/i.test(value) ? "boolean" : "text", dialect)).join(", ")});`).join("\n"); }
export function generateInClause(values: string[], type: "text" | "number" = "text", includeNull = false, dialect: SqlDialect = "generic") { const clean = values.map((value) => value.trim()).filter(Boolean); if (!clean.length && !includeNull) throw new Error("Enter at least one value."); const literals = clean.map((value) => sqlLiteral(value, type, dialect)); if (includeNull) literals.push("NULL"); return `IN (${literals.join(", ")})`; }
export function generateWhere(conditions: Array<{ column: string; operator: string; value: string; connector?: "AND" | "OR" }>, dialect: SqlDialect = "generic") { const allowed = new Set(["=", "!=", "<>", ">", ">=", "<", "<=", "LIKE", "NOT LIKE", "IS NULL", "IS NOT NULL"]); if (!conditions.length) throw new Error("Add at least one condition."); return `WHERE ${conditions.map((condition, index) => { const operator = condition.operator.toUpperCase(); if (!allowed.has(operator)) throw new Error(`Unsupported operator: ${operator}`); const value = operator.includes("NULL") ? "" : ` ${sqlLiteral(condition.value, /^-?\d+(?:\.\d+)?$/.test(condition.value) ? "number" : "text", dialect)}`; return `${index ? `${condition.connector ?? "AND"} ` : ""}${quoteIdentifier(condition.column, dialect)} ${operator}${value}`; }).join(" ")}`; }
export function generateCreateTable(table: string, columns: Array<{ name: string; type: string; nullable?: boolean; primary?: boolean }>, dialect: SqlDialect = "generic") { if (!columns.length) throw new Error("Add at least one column definition."); const allowedType = /^(?:INT|INTEGER|BIGINT|SMALLINT|TEXT|BOOLEAN|DATE|TIMESTAMP|DATETIME|REAL|FLOAT|DOUBLE|DECIMAL\(\d+(?:,\d+)?\)|VARCHAR\(\d+\)|CHAR\(\d+\)|JSON|BLOB|UUID)$/i; return `CREATE TABLE ${quoteIdentifier(table, dialect)} (\n${columns.map((column) => { if (!allowedType.test(column.type.trim())) throw new Error(`Unsupported type: ${column.type}`); return `  ${quoteIdentifier(column.name, dialect)} ${column.type.toUpperCase()}${column.primary ? " PRIMARY KEY" : ""}${column.nullable === false ? " NOT NULL" : ""}`; }).join(",\n")}\n);`; }
export function parseInsert(sql: string) { const match = sql.trim().match(/^INSERT\s+INTO\s+([\w."`\[\]]+)\s*\(([^)]+)\)\s*VALUES\s*([\s\S]+?);?$/i); if (!match) throw new Error("Expected INSERT INTO table (columns) VALUES (...)."); const columns = match[2].split(",").map((value) => value.trim().replace(/^["`\[]|["`\]]$/g, "")); const groups = [...match[3].matchAll(/\(([^()]*)\)/g)]; if (!groups.length) throw new Error("No VALUES rows were found."); const rows = groups.map((group) => group[1].match(/'(?:''|[^'])*'|[^,]+/g)?.map((value) => { const clean = value.trim(); if (/^NULL$/i.test(clean)) return null; if (clean.startsWith("'")) return clean.slice(1, -1).replaceAll("''", "'"); if (/^-?\d+(?:\.\d+)?$/.test(clean)) return Number(clean); return clean; }) ?? []); if (rows.some((row) => row.length !== columns.length)) throw new Error("A VALUES row does not match the column count."); return { table: match[1], columns, rows };
}
export function explainSql(sql: string, dialect: SqlDialect = "generic") { const validation = validateSql(sql, dialect); const upper = minifySql(sql).toUpperCase(); const steps: string[] = []; if (/^SELECT\b/.test(upper) || /^WITH\b/.test(upper)) steps.push("Reads rows using a SELECT query."); if (/\bFROM\b/.test(upper)) steps.push("Chooses the source table or subquery in the FROM clause."); if (/\bJOIN\b/.test(upper)) steps.push("Combines rows from multiple sources using one or more JOIN conditions."); if (/\bWHERE\b/.test(upper)) steps.push("Filters rows before grouping or projection using WHERE."); if (/\bGROUP BY\b/.test(upper)) steps.push("Groups matching rows before aggregate results are produced."); if (/\bHAVING\b/.test(upper)) steps.push("Filters grouped results using HAVING."); if (/\bORDER BY\b/.test(upper)) steps.push("Sorts the final result using ORDER BY."); if (/\bLIMIT\b|\bTOP\b|\bFETCH\b/.test(upper)) steps.push("Restricts the number of returned rows."); if (/^INSERT\b/.test(upper)) steps.push("Adds new rows to the target table."); if (/^UPDATE\b/.test(upper)) steps.push(`Updates matching rows.${/\bWHERE\b/.test(upper) ? "" : " No WHERE clause was detected, so every row may be affected."}`); if (/^DELETE\b/.test(upper)) steps.push(`Deletes rows.${/\bWHERE\b/.test(upper) ? "" : " No WHERE clause was detected, so every row may be affected."}`); if (!steps.length) steps.push("The query uses a statement pattern outside the explainer's supported structural subset."); return { dialect, validStructure: validation.valid, diagnostics: validation.diagnostics, steps, disclaimer: "Local deterministic explanation only. The query was not executed and no database query plan was inspected." };
}
