import { DataTable } from "../data";
import type { SqlDialect } from "./index";

export type KeywordCase = "upper" | "lower" | "preserve";
const KEYWORDS = new Set("select from where and or insert into values update set delete create table join inner left right full outer on as group by order having limit offset union all distinct case when then else end null is not like in exists primary key references default unique check returning with asc desc".split(" "));
const CLAUSES = ["SELECT", "FROM", "WHERE", "GROUP BY", "HAVING", "ORDER BY", "LIMIT", "OFFSET", "VALUES", "SET", "RETURNING", "UNION", "LEFT JOIN", "RIGHT JOIN", "FULL JOIN", "INNER JOIN", "JOIN"];

export interface SqlToken { type: "word" | "string" | "quoted" | "comment" | "symbol" | "space"; value: string; position: number }
export function tokenizeSql(sql: string): SqlToken[] {
  const tokens: SqlToken[] = []; let index = 0;
  while (index < sql.length) { const start = index; const char = sql[index];
    if (/\s/.test(char)) { while (/\s/.test(sql[index] ?? "")) index++; tokens.push({ type: "space", value: sql.slice(start, index), position: start }); continue; }
    if (char === "-" && sql[index + 1] === "-") { index += 2; while (index < sql.length && sql[index] !== "\n") index++; tokens.push({ type: "comment", value: sql.slice(start, index), position: start }); continue; }
    if (char === "/" && sql[index + 1] === "*") { index += 2; while (index < sql.length && !(sql[index] === "*" && sql[index + 1] === "/")) index++; if (index >= sql.length) throw new Error(`Unclosed block comment at character ${start + 1}.`); index += 2; tokens.push({ type: "comment", value: sql.slice(start, index), position: start }); continue; }
    if (["'", '"', "`", "["].includes(char)) { const close = char === "[" ? "]" : char; index++; while (index < sql.length) { if (sql[index] === close) { if (sql[index + 1] === close && close !== "]") { index += 2; continue; } index++; break; } index++; } if (sql[index - 1] !== close) throw new Error(`Unclosed quoted value at character ${start + 1}.`); tokens.push({ type: char === "'" ? "string" : "quoted", value: sql.slice(start, index), position: start }); continue; }
    if (/[A-Za-z0-9_$]/.test(char)) { index++; while (/[A-Za-z0-9_$]/.test(sql[index] ?? "")) index++; tokens.push({ type: "word", value: sql.slice(start, index), position: start }); continue; }
    index++; tokens.push({ type: "symbol", value: char, position: start });
  } return tokens;
}

function keyword(value: string, casing: KeywordCase) { if (!KEYWORDS.has(value.toLowerCase())) return value; return casing === "upper" ? value.toUpperCase() : casing === "lower" ? value.toLowerCase() : value; }
export function minifySql(sql: string) { const tokens = tokenizeSql(sql).filter((token) => token.type !== "comment" && token.type !== "space"); let output = ""; tokens.forEach((token, index) => { const previous = tokens[index - 1]; const needSpace = previous && ((["word", "string", "quoted"].includes(previous.type) && ["word", "string", "quoted"].includes(token.type)) || (previous.value === ")" && token.type === "word") || (previous.type === "word" && token.value === "(" && previous.value.toUpperCase() === "IN")); output += `${needSpace ? " " : ""}${token.value}`; }); return output.trim(); }

export function formatSql(sql: string, options: { keywordCase?: KeywordCase; indent?: number } = {}) { const casing = options.keywordCase ?? "upper"; const indent = " ".repeat(options.indent ?? 2); const compact = minifySql(sql); const tokens = tokenizeSql(compact).filter((token) => token.type !== "space"); let output = ""; let depth = 0; const newline = () => { output = output.trimEnd(); if (output) output += "\n" + indent.repeat(Math.max(0, depth)); };
  for (let index = 0; index < tokens.length; index++) { const token = tokens[index]; const two = `${token.value.toUpperCase()} ${tokens[index + 1]?.value.toUpperCase()}`; const clause = CLAUSES.includes(two) ? two : CLAUSES.includes(token.value.toUpperCase()) ? token.value.toUpperCase() : "";
    if (clause && output && !["AND", "OR"].includes(clause)) newline();
    if (clause === two) { output += `${keyword(token.value, casing)} ${keyword(tokens[++index].value, casing)} `; continue; }
    if (token.value === "(") { depth++; output += "("; }
    else if (token.value === ")") { depth = Math.max(0, depth - 1); output = output.trimEnd() + ")"; }
    else if (token.value === ",") { output = output.trimEnd() + ",\n" + indent.repeat(depth + 1); }
    else if (token.value === ";") output = output.trimEnd() + ";\n";
    else { const value = token.type === "word" ? keyword(token.value, casing) : token.value; const previous = output.at(-1); const noSpace = !output || previous === "(" || previous === "." || token.value === "."; output += `${noSpace ? "" : " "}${value}`; }
  } return output.trim(); }

export interface ParsedSqlStatement { kind: string; tokens: SqlToken[]; start: number; end: number }
export function parseSqlStatements(sql: string): ParsedSqlStatement[] { const tokens = tokenizeSql(sql).filter((token) => token.type !== "space" && token.type !== "comment"); const statements: ParsedSqlStatement[] = []; let current: SqlToken[] = []; let depth = 0; const push = () => { if (!current.length) return; statements.push({ kind: current[0].value.toUpperCase(), tokens: current, start: current[0].position, end: current.at(-1)!.position + current.at(-1)!.value.length }); current = []; };
  tokens.forEach((token) => { if (token.value === "(") depth++; if (token.value === ")") depth--; current.push(token); if (token.value === ";" && depth === 0) push(); }); push(); return statements;
}
export function validateSql(sql: string, dialect: SqlDialect = "generic") { const diagnostics: string[] = []; const warnings: string[] = []; if (!sql.trim()) diagnostics.push("SQL input is empty."); let statements: ParsedSqlStatement[] = []; try { statements = parseSqlStatements(sql); } catch (error) { diagnostics.push(error instanceof Error ? error.message : "Unable to tokenize SQL."); }
  statements.forEach((statement, statementIndex) => { const values = statement.tokens.map((token) => token.value.toUpperCase()); let depth = 0; statement.tokens.forEach((token) => { if (token.value === "(") depth++; if (token.value === ")") depth--; if (depth < 0) { diagnostics.push(`Statement ${statementIndex + 1}: unexpected closing parenthesis at character ${token.position + 1}.`); depth = 0; } }); if (depth) diagnostics.push(`Statement ${statementIndex + 1}: ${depth} opening parenthesis${depth === 1 ? " is" : "es are"} not closed.`);
    const first = values[0]; const supported = ["SELECT", "INSERT", "UPDATE", "DELETE", "CREATE", "ALTER", "DROP", "WITH", "MERGE", "TRUNCATE"]; if (first && !supported.includes(first)) diagnostics.push(`Statement ${statementIndex + 1}: unsupported or unrecognized starting keyword ${first}.`);
    const requireAfter = (keywordValue: string, message: string) => { const index = values.indexOf(keywordValue); if (index < 0 || !statement.tokens[index + 1] || statement.tokens[index + 1].value === ";") diagnostics.push(`Statement ${statementIndex + 1}: ${message}`); };
    if (first === "SELECT") { requireAfter("SELECT", "SELECT requires a projection expression."); if (values[1] === "FROM") diagnostics.push(`Statement ${statementIndex + 1}: SELECT requires a projection expression before FROM.`); }
    if (first === "INSERT") { if (values[1] !== "INTO") diagnostics.push(`Statement ${statementIndex + 1}: INSERT must be followed by INTO.`); else requireAfter("INTO", "INTO requires a target table."); if (!values.includes("VALUES") && !values.includes("SELECT")) diagnostics.push(`Statement ${statementIndex + 1}: INSERT requires VALUES or a SELECT source.`); }
    if (first === "UPDATE") { requireAfter("UPDATE", "UPDATE requires a target table."); if (values[1] === "SET") diagnostics.push(`Statement ${statementIndex + 1}: UPDATE requires a target table before SET.`); const setIndex = values.indexOf("SET"); if (setIndex < 0) diagnostics.push(`Statement ${statementIndex + 1}: UPDATE requires SET.`); else { requireAfter("SET", "SET requires at least one assignment."); const assignmentEnd = [values.indexOf("WHERE", setIndex + 1), values.indexOf("RETURNING", setIndex + 1), values.length].filter((index) => index >= 0).sort((a, b) => a - b)[0]; if (!values.slice(setIndex + 1, assignmentEnd).includes("=")) diagnostics.push(`Statement ${statementIndex + 1}: SET requires an assignment using =.`); } if (!values.includes("WHERE")) warnings.push(`Statement ${statementIndex + 1}: UPDATE has no WHERE clause and may affect every row.`); }
    if (first === "DELETE") { if (values[1] !== "FROM") diagnostics.push(`Statement ${statementIndex + 1}: DELETE must be followed by FROM.`); else requireAfter("FROM", "FROM requires a target table."); if (!values.includes("WHERE")) warnings.push(`Statement ${statementIndex + 1}: DELETE has no WHERE clause and may affect every row.`); }
    if (first === "CREATE" && values[1] !== "TABLE") diagnostics.push(`Statement ${statementIndex + 1}: this validator currently supports CREATE TABLE only.`);
    if (dialect !== "mysql" && dialect !== "generic" && statement.tokens.some((token) => token.type === "quoted" && token.value.startsWith("`"))) diagnostics.push(`Statement ${statementIndex + 1}: backtick identifiers are not enabled for ${dialect}.`);
    if (dialect !== "sql-server" && dialect !== "generic" && statement.tokens.some((token) => token.type === "quoted" && token.value.startsWith("["))) diagnostics.push(`Statement ${statementIndex + 1}: bracket identifiers are not enabled for ${dialect}.`);
    if ((dialect === "sql-server" || dialect === "oracle") && values.includes("LIMIT")) diagnostics.push(`Statement ${statementIndex + 1}: LIMIT is not supported by the selected ${dialect} profile.`);
  });
  return { valid: diagnostics.length === 0, diagnostics, warnings, dialect, parsedStatements: statements.map(({ kind, start, end }) => ({ kind, start, end })), scope: "Token-parser validation for the documented SQL subset; vendor-specific grammar is not executed." };
}

export function quoteIdentifier(identifier: string, dialect: SqlDialect) { if (!/^[A-Za-z_][A-Za-z0-9_$]*(?:\.[A-Za-z_][A-Za-z0-9_$]*)*$/.test(identifier)) throw new Error(`Invalid SQL identifier: ${identifier}`); const quote = dialect === "mysql" ? ["`", "`"] : dialect === "sql-server" ? ["[", "]"] : ['"', '"']; return identifier.split(".").map((part) => `${quote[0]}${part}${quote[1]}`).join("."); }
export function sqlLiteral(value: string, type: "text" | "number" | "boolean" | "null" = "text", dialect: SqlDialect = "generic") { if (type === "null" || value.toLowerCase() === "null") return "NULL"; if (type === "number") { if (!/^-?(?:\d+|\d*\.\d+)$/.test(value.trim())) throw new Error(`Invalid numeric value: ${value}`); return value.trim(); } if (type === "boolean") return /^(true|1)$/i.test(value.trim()) ? (dialect === "sql-server" ? "1" : "TRUE") : (dialect === "sql-server" ? "0" : "FALSE"); return `'${value.replaceAll("'", "''")}'`; }
export function tableToInsert(table: DataTable, tableName: string, dialect: SqlDialect = "generic") { if (!table.rows.length) throw new Error("At least one data row is required."); const target = quoteIdentifier(tableName, dialect); const columns = table.headers.map((header) => quoteIdentifier(header, dialect)).join(", "); return table.rows.map((row) => `INSERT INTO ${target} (${columns}) VALUES (${row.map((value) => sqlLiteral(value, value === "" ? "null" : /^-?\d+(?:\.\d+)?$/.test(value) ? "number" : /^(true|false)$/i.test(value) ? "boolean" : "text", dialect)).join(", ")});`).join("\n"); }
export function generateInClause(values: string[], type: "text" | "number" = "text", includeNull = false, dialect: SqlDialect = "generic") { const clean = values.map((value) => value.trim()).filter(Boolean); if (!clean.length && !includeNull) throw new Error("Enter at least one value."); const literals = clean.map((value) => sqlLiteral(value, type, dialect)); if (includeNull) literals.push("NULL"); return `IN (${literals.join(", ")})`; }
export function generateWhere(conditions: Array<{ column: string; operator: string; value: string; connector?: "AND" | "OR" }>, dialect: SqlDialect = "generic") { const allowed = new Set(["=", "!=", "<>", ">", ">=", "<", "<=", "LIKE", "NOT LIKE", "IS NULL", "IS NOT NULL"]); if (!conditions.length) throw new Error("Add at least one condition."); return `WHERE ${conditions.map((condition, index) => { const operator = condition.operator.toUpperCase(); if (!allowed.has(operator)) throw new Error(`Unsupported operator: ${operator}`); const value = operator.includes("NULL") ? "" : ` ${sqlLiteral(condition.value, /^-?\d+(?:\.\d+)?$/.test(condition.value) ? "number" : "text", dialect)}`; return `${index ? `${condition.connector ?? "AND"} ` : ""}${quoteIdentifier(condition.column, dialect)} ${operator}${value}`; }).join(" ")}`; }
export function generateCreateTable(table: string, columns: Array<{ name: string; type: string; nullable?: boolean; primary?: boolean }>, dialect: SqlDialect = "generic") { if (!columns.length) throw new Error("Add at least one column definition."); const allowedType = /^(?:INT|INTEGER|BIGINT|SMALLINT|TEXT|BOOLEAN|DATE|TIMESTAMP|DATETIME|REAL|FLOAT|DOUBLE|DECIMAL\(\d+(?:,\d+)?\)|VARCHAR\(\d+\)|CHAR\(\d+\)|JSON|BLOB|UUID)$/i; return `CREATE TABLE ${quoteIdentifier(table, dialect)} (\n${columns.map((column) => { if (!allowedType.test(column.type.trim())) throw new Error(`Unsupported type: ${column.type}`); return `  ${quoteIdentifier(column.name, dialect)} ${column.type.toUpperCase()}${column.primary ? " PRIMARY KEY" : ""}${column.nullable === false ? " NOT NULL" : ""}`; }).join(",\n")}\n);`; }
export function generateUpdate(table: string, assignments: Array<{ column: string; value: string }>, conditions: Array<{ column: string; operator: string; value: string; connector?: "AND" | "OR" }>, dialect: SqlDialect = "generic") { if (!assignments.length) throw new Error("Add at least one SET assignment."); if (!conditions.length) throw new Error("A WHERE condition is required. DevBite will not generate an unrestricted UPDATE statement."); const set = assignments.map(({ column, value }) => `${quoteIdentifier(column, dialect)} = ${sqlLiteral(value, /^-?\d+(?:\.\d+)?$/.test(value) ? "number" : /^(true|false)$/i.test(value) ? "boolean" : "text", dialect)}`).join(", "); return `UPDATE ${quoteIdentifier(table, dialect)} SET ${set} ${generateWhere(conditions, dialect)};`; }
export function generateDelete(table: string, conditions: Array<{ column: string; operator: string; value: string; connector?: "AND" | "OR" }>, dialect: SqlDialect = "generic") { if (!conditions.length) throw new Error("A WHERE condition is required. DevBite will not generate an unrestricted DELETE statement."); return `DELETE FROM ${quoteIdentifier(table, dialect)} ${generateWhere(conditions, dialect)};`; }
export function parseInsert(sql: string) { const match = sql.trim().match(/^INSERT\s+INTO\s+([\w."`\[\]]+)\s*\(([^)]+)\)\s*VALUES\s*([\s\S]+?);?$/i); if (!match) throw new Error("Expected INSERT INTO table (columns) VALUES (...)."); const columns = match[2].split(",").map((value) => value.trim().replace(/^["`\[]|["`\]]$/g, "")); const groups = [...match[3].matchAll(/\(([^()]*)\)/g)]; if (!groups.length) throw new Error("No VALUES rows were found."); const rows = groups.map((group) => group[1].match(/'(?:''|[^'])*'|[^,]+/g)?.map((value) => { const clean = value.trim(); if (/^NULL$/i.test(clean)) return null; if (clean.startsWith("'")) return clean.slice(1, -1).replaceAll("''", "'"); if (/^-?\d+(?:\.\d+)?$/.test(clean)) return Number(clean); return clean; }) ?? []); if (rows.some((row) => row.length !== columns.length)) throw new Error("A VALUES row does not match the column count."); return { table: match[1], columns, rows };
}
export function explainSql(sql: string, dialect: SqlDialect = "generic") { const validation = validateSql(sql, dialect); const upper = minifySql(sql).toUpperCase(); const steps: string[] = []; if (/^SELECT\b/.test(upper) || /^WITH\b/.test(upper)) steps.push("Reads rows using a SELECT query."); if (/\bFROM\b/.test(upper)) steps.push("Chooses the source table or subquery in the FROM clause."); if (/\bJOIN\b/.test(upper)) steps.push("Combines rows from multiple sources using one or more JOIN conditions."); if (/\bWHERE\b/.test(upper)) steps.push("Filters rows before grouping or projection using WHERE."); if (/\bGROUP BY\b/.test(upper)) steps.push("Groups matching rows before aggregate results are produced."); if (/\bHAVING\b/.test(upper)) steps.push("Filters grouped results using HAVING."); if (/\bORDER BY\b/.test(upper)) steps.push("Sorts the final result using ORDER BY."); if (/\bLIMIT\b|\bTOP\b|\bFETCH\b/.test(upper)) steps.push("Restricts the number of returned rows."); if (/^INSERT\b/.test(upper)) steps.push("Adds new rows to the target table."); if (/^UPDATE\b/.test(upper)) steps.push(`Updates matching rows.${/\bWHERE\b/.test(upper) ? "" : " No WHERE clause was detected, so every row may be affected."}`); if (/^DELETE\b/.test(upper)) steps.push(`Deletes rows.${/\bWHERE\b/.test(upper) ? "" : " No WHERE clause was detected, so every row may be affected."}`); if (!steps.length) steps.push("The query uses a statement pattern outside the explainer's supported structural subset."); return { dialect, validStructure: validation.valid, diagnostics: validation.diagnostics, steps, disclaimer: "Local deterministic explanation only. The query was not executed and no database query plan was inspected." };
}
